### ISSUE TITLE
@Timestamped could be a method-level annotation

### ISSUE THREAD

**Issue by qualidafial** [zikani03/jdbi-utils#2]
`@BindingAnnotation` isn't (yet) equipped for annotations on the method level, but `@SqlStatementCustomizingAnnotation` is, and you'll have access to parameter binding through that.

**Comment by zikani03** [comment]
The annotation is now both a method-level and parameter-level annotation with the subtle difference that the parameter-level annotation writes the datetime values onto the fields of the object argument (so long as it's a Java Bean).
Do you think this is appropriate or there should just be the method-level annotation? @qualidafial

**Comment by qualidafial** [comment]
That's probably a matter of taste. Personally I'd probably just go with method-level annotation, since there's nothing parameter-specific about it now.
